# Generated by Django 3.0 on 2021-08-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество покупаемого товара'),
        ),
        migrations.AlterField(
            model_name='supplyrecord',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество поступаемого товара'),
        ),
    ]
